
secretKey: secret123
spring:
  profiles: Danya
  datasource:
    password: xna004
server:
  port: 8001
---
spring:
  profiles: Drew
  datasource:
    password: kkh753
---
spring:
  profiles:
    active: Danya