securityServiceUrl: "http://localhost:8002/generateToken"
spring:
  profiles: Danya
  datasource:
    password: xna004
server:
  port: 8001
logging:
  level:
    ru.lightsoff.authentication: DEBUG
---
spring:
  profiles: Drew
  datasource:
    password: kkh753
---
spring:
  profiles:
    active: Danya